# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/inference/inference.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'proto/inference/inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fproto/inference/inference.proto\x12\tinference\",\n\x0b\x43hatMessage\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\xd4\x01\n\x0fGenerateRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06job_id\x18\x02 \x01(\t\x12\r\n\x05model\x18\x03 \x01(\t\x12(\n\x08messages\x18\x04 \x03(\x0b\x32\x16.inference.ChatMessage\x12\x12\n\nmax_tokens\x18\x05 \x01(\x05\x12\x13\n\x0btemperature\x18\x06 \x01(\x02\x12\x0e\n\x06stream\x18\x07 \x01(\x08\x12\x17\n\x0forganization_id\x18\x08 \x01(\t\x12\x12\n\nproject_id\x18\t \x01(\t\"T\n\nTokenUsage\x12\x15\n\rprompt_tokens\x18\x01 \x01(\x05\x12\x19\n\x11\x63ompletion_tokens\x18\x02 \x01(\x05\x12\x14\n\x0ctotal_tokens\x18\x03 \x01(\x05\"\xa1\x01\n\x10GenerateResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06job_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x0c\n\x04\x64one\x18\x04 \x01(\x08\x12\x15\n\rfinish_reason\x18\x05 \x01(\t\x12$\n\x05usage\x18\x06 \x01(\x0b\x32\x15.inference.TokenUsage\x12\r\n\x05\x65rror\x18\x07 \x01(\t\"\'\n\x12HealthCheckRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\"?\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x18\n\x10supported_models\x18\x02 \x03(\t2\xa7\x01\n\x10InferenceService\x12\x45\n\x08Generate\x12\x1a.inference.GenerateRequest\x1a\x1b.inference.GenerateResponse0\x01\x12L\n\x0bHealthCheck\x12\x1d.inference.HealthCheckRequest\x1a\x1e.inference.HealthCheckResponseB:Z8github.com/Faithful001/aegis/proto/inference;inferencepbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.inference.inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/Faithful001/aegis/proto/inference;inferencepb'
  _globals['_CHATMESSAGE']._serialized_start=46
  _globals['_CHATMESSAGE']._serialized_end=90
  _globals['_GENERATEREQUEST']._serialized_start=93
  _globals['_GENERATEREQUEST']._serialized_end=305
  _globals['_TOKENUSAGE']._serialized_start=307
  _globals['_TOKENUSAGE']._serialized_end=391
  _globals['_GENERATERESPONSE']._serialized_start=394
  _globals['_GENERATERESPONSE']._serialized_end=555
  _globals['_HEALTHCHECKREQUEST']._serialized_start=557
  _globals['_HEALTHCHECKREQUEST']._serialized_end=596
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=598
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=661
  _globals['_INFERENCESERVICE']._serialized_start=664
  _globals['_INFERENCESERVICE']._serialized_end=831
# @@protoc_insertion_point(module_scope)
